### ISSUE TITLE
Indexer encounter panick when scanning for UTXO

### ISSUE THREAD

**Issue by Zealy-Rockx** [AvaLido/mpc-controller#342]
mpc_controller1 | {"level":"DEBUG","ts":"2023-03-08T09:57:46.278506746Z","caller":"keygen/task.go:157","msg":"failed to report generated public key","error":"failed to call contract: insufficient funds for gas * price + value: address 0xC9e736Bda0d75ce0A8CBA0500c9f6D3EE6fE317a have (0) want (15309645192589110)"}
mpc_controller1 | {"level":"DEBUG","ts":"2023-03-08T09:57:46.951305368Z","caller":"indexer/indexer.go:91","msg":"scanning delegators"}
mpc_controller1 | {"level":"DEBUG","ts":"2023-03-08T09:57:46.958702298Z","caller":"indexer/indexer.go:65","msg":"finished scanning delegators"}
mpc_controller1 | {"level":"DEBUG","ts":"2023-03-08T09:57:46.958932028Z","caller":"indexer/indexer.go:135","msg":"scanning utxos"}
mpc_controller1 | panic: runtime error: invalid memory address or nil pointer dereference
mpc_controller1 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd7609a]
mpc_controller1 | 
mpc_controller1 | goroutine 213 [running]:
mpc_controller1 | github.com/avalido/mpc-controller/indexer.(*Indexer).scanUTXOs(0xc0006b69b0, {0x14fc978, 0xc00071a040})
mpc_controller1 |       /go/src/github.com/avalido/mpc-controller/indexer/indexer.go:149 +0x1ba
mpc_controller1 | github.com/avalido/mpc-controller/indexer.(*Indexer).Start.func1()
mpc_controller1 |       /go/src/github.com/avalido/mpc-controller/indexer/indexer.go:67 +0x245
mpc_controller1 | created by github.com/avalido/mpc-controller/indexer.(*Indexer).Start
mpc_controller1 |       /go/src/github.com/avalido/mpc-controller/indexer/indexer.go:50 +0x130
zealy@pop-os:~/Rockx/internal-testnet$ task services:restoreWithMockMpcServer

**Comment by Zealy-Rockx** [comment]
Root cause: key not generated and mpc-controller doesn't deal with this situation.
